/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CommandCenterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "command-center-dashboard";
var DEFAULT_SETTINGS = {
  visibleDomains: {
    varix: true,
    ssa: true,
    smfc: true,
    tessora: true,
    cafelive: true,
    veavii: true,
    mangara: true,
    "pokecard-ph": true,
    beautybooth: true,
    kabiyahe: true,
    "oishii-nori": true,
    istoria: true,
    "mpi-rag": true
  },
  openOnStartup: true,
  showHeroTile: true,
  showSkillButtons: true,
  showSchedulePanel: true,
  showHeadlinesPanel: true,
  showTodaySection: true,
  showSessionSummary: true,
  showHeatmap: true,
  lastSync: 0,
  syncCli: "opencode",
  staleDays: 3,
  criticalDays: 7,
  activityLog: {}
};
var DOMAINS = [
  { key: "varix", name: "Varix", path: "projects/varix", status: "In Progress", liveUrl: "https://www.varix.work" },
  { key: "ssa", name: "SSA", path: "projects/ssa", status: "In Progress" },
  { key: "smfc", name: "SMFC Command Suite", path: "projects/smfc", status: "Complete", liveUrl: "https://dashboard-web-two-sigma.vercel.app/login" },
  { key: "tessora", name: "Tessora", path: "projects/tessora", status: "In Progress" },
  { key: "cafelive", name: "CafeLive", path: "projects/founder/cafelive", status: "In Progress", liveUrl: "https://cafetemp-three.vercel.app" },
  { key: "veavii", name: "Veavii", path: "projects/founder/veavii", status: "Complete", liveUrl: "https://vivea-three.vercel.app" },
  { key: "mangara", name: "Mangara", path: "projects/founder/mangara", status: "In Progress", liveUrl: "https://mangara-iota.vercel.app" },
  { key: "pokecard-ph", name: "PokeCard PH", path: "projects/founder/pokecard-ph", status: "In Progress", liveUrl: "https://pokecard-ph.vercel.app" },
  { key: "beautybooth", name: "BeautyBooth", path: "projects/founder/beautybooth", status: "In Progress" },
  { key: "kabiyahe", name: "Kabiyahe", path: "projects/founder/kabiyahe", status: "Planning" },
  { key: "oishii-nori", name: "Oishii Nori", path: "projects/varix/oishii-nori", status: "In Progress" },
  { key: "istoria", name: "Istoria Coffee", path: "projects/founder/istoria", status: "Complete", liveUrl: "https://istoria-vince-tamis.vercel.app" },
  { key: "mpi-rag", name: "MPI RAG", path: "projects/ssa/mpi-rag", status: "In Progress" }
];
var DOMAIN_KEYWORDS = {
  "oishii-nori": ["oishii", "nori", "oishii nori"],
  "tessora": ["tessora"],
  "cafelive": ["cafelive", "cafe live", "cafetemp"],
  "veavii": ["veavii", "vivea"],
  "mangara": ["mangara"],
  "pokecard-ph": ["pokecard", "pokemon card", "pokecard ph"],
  "beautybooth": ["beautybooth", "beauty booth"],
  "kabiyahe": ["kabiyahe"],
  "smfc": ["smfc", "saint michael pos", "saint michael"],
  "mpi-rag": ["mpi rag", "mpi-rag", "mpi thesis"],
  "istoria": ["istoria"],
  "ssa": ["ssa", "summit sports academy", "sports academy"],
  "varix": ["varix"]
};
var GIT_REPOS = [
  { name: "CafeLive", path: "D:\\CAFETEMP" },
  { name: "PokeCard PH", path: "D:\\POKECARDPH" },
  { name: "Veavii", path: "D:\\Vi vea" },
  { name: "Mangara", path: "D:\\mangara" }
];
var HANDOFF_REPOS = [
  { domain: "cafelive", name: "CafeLive", path: "D:\\CAFETEMP\\SESSION_HANDOFF.md" },
  { domain: "oishii-nori", name: "Oishii Nori", path: "D:\\ioshinori\\oishii-nori-command-suite\\SESSION_HANDOFF.md" },
  { domain: "istoria", name: "Istoria Coffee", path: "D:\\istoria2\\SESSION_HANDOFF.md" },
  { domain: "veavii", name: "Veavii", path: "D:\\Vi vea\\SESSION_HANDOFF.md" },
  { domain: "smfc", name: "SMFC Command Suite", path: "D:\\SMFC_POS\\SESSION_HANDOFF.md" },
  { domain: "tessora", name: "Tessora", path: "D:\\tessora\\SESSION_HANDOFF.md" },
  { domain: "pokecard-ph", name: "PokeCard PH", path: "D:\\POKECARDPH\\SESSION_HANDOFF.md" },
  { domain: "mangara", name: "Mangara", path: "D:\\mangara\\SESSION_HANDOFF.md" }
];
var STATUS_SYNC_PROMPT = [
  "You are syncing the Obsidian command suite vault at D:\\OBSIDIAN\\COMMAND SUITE.",
  "Read every SESSION_HANDOFF.md listed below, plus the vault's ops/today.md, ops/metrics.md,",
  "ops/varix-open-items.md, ops/headlines.md, and each projects/<domain>/STATUS.md.",
  "Update stale STATUS.md session summaries, current phases, progress bars, and blocker lists,",
  "and refresh ops entries so they reflect the handoffs. Follow the filing conventions in CLAUDE.md.",
  "Do not commit anything.",
  "Handoffs:",
  `- ${HANDOFF_REPOS.map((r) => r.path).join("\n- ")}`
].join(" ");
var KNOWN_ACTIVITY = [
  ["2026-05-18", 1],
  // MPI RAG
  ["2026-06-09", 1],
  // CafeLive
  ["2026-06-20", 1],
  // CafeLive
  ["2026-06-21", 1],
  // CafeLive
  ["2026-06-22", 1],
  // CafeLive
  ["2026-06-23", 1],
  // CafeLive
  ["2026-06-25", 1],
  // CafeLive
  ["2026-07-22", 2],
  // Varix + Tessora
  ["2026-07-23", 1],
  // Varix
  ["2026-07-24", 1],
  // Varix (mid-week)
  ["2026-07-25", 2],
  // Varix + Tessora
  ["2026-07-26", 1],
  // Varix
  ["2026-07-27", 4],
  // Varix + Tessora + Tessora app + Founders
  ["2026-07-28", 1],
  // Istoria
  ["2026-07-29", 1],
  // Istoria
  ["2026-07-31", 1],
  // CafeLive
  ["2026-08-01", 1],
  // CafeLive
  ["2026-08-02", 1],
  // SMFC
  ["2026-08-03", 1],
  // SMFC
  ["2026-08-04", 3],
  // SMFC + CafeLive + Command Suite
  ["2026-08-05", 2],
  // CafeLive + messaging
  ["2026-08-06", 4],
  // CafeLive + Veavii + landing page
  ["2026-08-07", 1],
  // BeautyBooth
  ["2026-08-08", 1],
  // CafeLive (weekend)
  ["2026-08-09", 1],
  // MPI RAG
  ["2026-08-10", 2],
  // Varix + MPI RAG
  ["2026-08-11", 5],
  // Varix + PokeCard + Mangara + session + vault
  ["2026-08-12", 1],
  // PokeCard
  ["2026-08-13", 2],
  // PokeCard + Kabiyahe
  ["2026-08-14", 1],
  // PokeCard (mid-week)
  ["2026-08-15", 1],
  // Varix (mid-week)
  ["2026-08-16", 1],
  // PokeCard (weekend)
  ["2026-08-17", 1],
  // PokeCard
  ["2026-08-18", 3],
  // PokeCard + MPI RAG + MPI session
  ["2026-08-19", 1],
  // Oishii Nori (prep)
  ["2026-08-20", 2],
  // Oishii Nori + session handoff
  ["2026-08-21", 3]
  // Command Suite + metrics scan + heatmap
];
function scanGitRepos() {
  const counts = /* @__PURE__ */ new Map();
  let execSync;
  try {
    execSync = require("child_process").execSync;
  } catch (e) {
    try {
      execSync = window.require("electron").remote.require("child_process").execSync;
    } catch (e2) {
      return counts;
    }
  }
  for (const repo of GIT_REPOS) {
    try {
      const result = execSync(
        `git -C "${repo.path}" log --since="90 days ago" --format="%ad" --date=short`,
        { encoding: "utf-8", timeout: 5e3, windowsHide: true }
      );
      const dates = result.split("\n").filter((d) => d.trim());
      for (const date of dates) {
        counts.set(date, (counts.get(date) || 0) + 1);
      }
    } catch (e) {
    }
  }
  return counts;
}
function scanSessionHandoffs() {
  const counts = /* @__PURE__ */ new Map();
  for (const [date, count] of KNOWN_ACTIVITY) {
    counts.set(date, (counts.get(date) || 0) + count);
  }
  return counts;
}
var SYNC_SECTION_OPEN = /pending|open item|action needed|outstanding|blocker|not started|todo|to do/i;
var SYNC_SECTION_CLOSED = /resolved|completed|done|closed|fixed|decided/i;
function readHandoffFile(entry) {
  const base = {
    domain: entry.domain,
    name: entry.name,
    path: entry.path,
    found: false,
    lastUpdated: "",
    statusLine: "",
    openItems: 0,
    snippet: ""
  };
  let fs;
  try {
    fs = require("fs");
  } catch (e) {
    try {
      fs = window.require("electron").remote.require("fs");
    } catch (e2) {
      return base;
    }
  }
  let content;
  try {
    content = fs.readFileSync(entry.path, "utf-8");
  } catch (e) {
    return base;
  }
  const info = { ...base, found: true };
  const lines = content.split("\n");
  const dateMatch = content.match(/(?:\*\*Updated:\*\*|[Ll]ast updated:?|[Uu]pdated:?)(\s*"?)(\d{4}-\d{2}-\d{2})/) || content.match(/(?:\*\*Date:\*\*|[Hh]andoff \()(\s*"?)(\d{4}-\d{2}-\d{2})/);
  if (dateMatch) {
    info.lastUpdated = dateMatch[2];
  } else {
    const bareDate = content.match(/\d{4}-\d{2}-\d{2}/);
    if (bareDate)
      info.lastUpdated = bareDate[0];
  }
  const statusMatch = content.match(/^\s*(?:>\s*)?\*\*(?:Build )?[Ss]tatus.*$/m);
  if (statusMatch) {
    info.statusLine = statusMatch[0].replace(/^[\s>*-]+/, "").trim();
  }
  let counting = false;
  for (const raw of lines) {
    const t = raw.trim();
    const heading = t.match(/^#{1,4}\s+(.*)/);
    if (heading) {
      counting = SYNC_SECTION_OPEN.test(heading[1]) && !SYNC_SECTION_CLOSED.test(heading[1]);
      continue;
    }
    const boldMarker = t.match(/^\*\*(.+?):?\*\*/);
    if (boldMarker) {
      if (SYNC_SECTION_CLOSED.test(boldMarker[1])) {
        counting = false;
        continue;
      }
      const restIsEmpty = t.replace(/^\*\*.+?\*\*:?\s*/, "") === "";
      if (restIsEmpty && SYNC_SECTION_OPEN.test(boldMarker[1])) {
        counting = true;
        continue;
      }
    }
    if (counting && /^(\s*-\s+|\s*\d+\.\s+)/.test(raw)) {
      info.openItems++;
    }
  }
  if (info.statusLine) {
    info.snippet = info.statusLine;
  } else {
    for (const line of lines) {
      const t = line.trim().replace(/^-\s+/, "");
      if (t && !t.startsWith("#") && !t.startsWith(">") && !t.startsWith("|") && t.length > 40) {
        info.snippet = t;
        break;
      }
    }
  }
  return info;
}
function scanHandoffs() {
  return HANDOFF_REPOS.map(readHandoffFile);
}
function readVaultStatus(domain, vaultRoot) {
  const base = {
    domain: domain.key,
    name: domain.name,
    found: false,
    lastUpdated: "",
    phase: "",
    progressPct: null,
    blockersOpen: 0
  };
  let fs;
  try {
    fs = require("fs");
  } catch (e) {
    return base;
  }
  let content;
  try {
    content = fs.readFileSync(`${vaultRoot}\\${domain.path}\\STATUS.md`, "utf-8");
  } catch (e) {
    return base;
  }
  const info = { ...base, found: true };
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() !== "## Last Updated")
      continue;
    for (let j = i + 1; j < lines.length; j++) {
      const t = lines[j].trim();
      if (!t)
        continue;
      const m = t.match(/(\d{4}-\d{2}-\d{2})/);
      if (m)
        info.lastUpdated = m[1];
      break;
    }
    break;
  }
  for (let i = 0; i < lines.length; i++) {
    if (!/^#{1,4}\s+.*Current Phase/i.test(lines[i]))
      continue;
    for (let j = i + 1; j < lines.length; j++) {
      const t = lines[j].trim();
      if (!t || t.startsWith("```"))
        continue;
      if (t.startsWith("#"))
        break;
      info.phase = t;
      break;
    }
    break;
  }
  for (let i = 0; i < lines.length; i++) {
    if (!/^#{1,4}\s+.*Progress/i.test(lines[i]))
      continue;
    for (let j = i + 1; j < Math.min(i + 6, lines.length); j++) {
      const m = lines[j].match(/(\d{1,3})%/);
      if (m) {
        info.progressPct = parseInt(m[1], 10);
        break;
      }
    }
    break;
  }
  let inBlockers = false;
  for (const raw of lines) {
    const heading = raw.trim().match(/^#{1,4}\s+(.*)/);
    if (heading) {
      inBlockers = /blocker/i.test(heading[1]);
      continue;
    }
    if (inBlockers && /^\s*-\s+\[ \]/.test(raw))
      info.blockersOpen++;
  }
  return info;
}
function scanVaultStatuses(vaultRoot) {
  return DOMAINS.map((d) => readVaultStatus(d, vaultRoot));
}
function mergeActivityMaps(...maps) {
  const merged = /* @__PURE__ */ new Map();
  for (const map of maps) {
    for (const [date, count] of map) {
      merged.set(date, (merged.get(date) || 0) + count);
    }
  }
  return merged;
}
var CommandCenterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.activityData = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new DashboardView(leaf, this));
    this.addRibbonIcon("layout-dashboard", "Command Center", () => this.activateView());
    this.addCommand({ id: "open-dashboard", name: "Open Dashboard", callback: () => this.activateView() });
    this.addCommand({ id: "add-task", name: "Add Today's Task", callback: () => this.openTaskModal() });
    this.addSettingTab(new CommandCenterSettingTab(this.app, this));
    this.refreshActivityData();
    if (this.settings.openOnStartup) {
      this.app.workspace.onLayoutReady(() => this.activateView());
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE, active: true });
      }
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  openTaskModal() {
    new TaskInputModal(this.app, this).open();
  }
  refreshActivityData() {
    var _a;
    const gitData = scanGitRepos();
    const handoffData = scanSessionHandoffs();
    const vaultLog = new Map(
      Object.entries((_a = this.settings.activityLog) != null ? _a : {})
    );
    this.activityData = mergeActivityMaps(gitData, handoffData, vaultLog);
  }
  // Marks today as an active day (capped at 1 contribution/day) whenever a
  // skill runs from the dashboard, so the heatmap reflects real vault usage.
  async recordVaultActivity() {
    var _a, _b;
    const key = fmtDate(/* @__PURE__ */ new Date());
    const log = (_a = this.settings.activityLog) != null ? _a : {};
    log[key] = Math.max((_b = log[key]) != null ? _b : 0, 1);
    this.settings.activityLog = log;
    await this.saveSettings();
    this.refreshActivityData();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function insertUnderSection(content, heading, newLines, dedupe) {
  if (dedupe) {
    const existing = new Set(
      content.split("\n").filter((l) => l.trim().startsWith("- [")).map((l) => l.replace(/^-\s*\[[ x]\]\s*/, "").trim())
    );
    newLines = newLines.filter((l) => !existing.has(l.replace(/^-\s*\[[ x]\]\s*/, "").trim()));
    if (newLines.length === 0)
      return content;
  }
  if (content.includes(heading)) {
    const lines = content.split("\n");
    let headingIdx = -1;
    let insertIdx = -1;
    let inSection = false;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trim() === heading) {
        headingIdx = i;
        inSection = true;
        continue;
      }
      if (inSection) {
        if (lines[i].startsWith("## ") || lines[i].startsWith("#") && !lines[i].startsWith("##")) {
          insertIdx = i;
          break;
        }
        if (lines[i].trim().startsWith("- [")) {
          insertIdx = i + 1;
        }
      }
    }
    if (insertIdx === -1)
      insertIdx = headingIdx + 1;
    lines.splice(insertIdx, 0, ...newLines);
    return lines.join("\n");
  }
  return content + "\n\n" + heading + "\n" + newLines.join("\n");
}
var TaskInputModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onSave) {
    super(app);
    this.detectedDomain = null;
    this.plugin = plugin;
    this.onSave = onSave;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cc-modal");
    contentEl.createEl("h2", { text: "Add Today's Task", cls: "cc-modal-title" });
    const inputWrapper = contentEl.createDiv({ cls: "cc-modal-input-wrapper" });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "cc-modal-input",
      attr: { placeholder: "What needs to happen?" }
    });
    const routePreview = contentEl.createDiv({ cls: "cc-modal-route-preview" });
    routePreview.createSpan({ cls: "cc-modal-route-label", text: "Routes to: " });
    const routeTarget = routePreview.createSpan({ cls: "cc-modal-route-target", text: "none detected" });
    input.addEventListener("input", () => {
      const val = input.value.toLowerCase();
      this.detectedDomain = null;
      for (const [key, keywords] of Object.entries(DOMAIN_KEYWORDS)) {
        for (const kw of keywords) {
          if (val.includes(kw)) {
            this.detectedDomain = key;
            const domain = DOMAINS.find((d) => d.key === key);
            routeTarget.setText(domain ? domain.name : key);
            routeTarget.addClass("cc-modal-route-detected");
            return;
          }
        }
      }
      routeTarget.setText("none detected");
      routeTarget.removeClass("cc-modal-route-detected");
    });
    const btnRow = contentEl.createDiv({ cls: "cc-modal-btn-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel", cls: "cc-modal-btn cc-modal-btn-cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const addBtn = btnRow.createEl("button", { text: "Add Task", cls: "cc-modal-btn cc-modal-btn-add" });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        addBtn.click();
    });
    let submitting = false;
    addBtn.addEventListener("click", async () => {
      var _a;
      if (submitting)
        return;
      const text = input.value.trim();
      if (!text)
        return;
      submitting = true;
      addBtn.disabled = true;
      const slug = this.detectedDomain || "";
      const routeLine = slug ? `- [ ] ${text} \u2192 ${slug}` : `- [ ] ${text}`;
      try {
        const existingToday = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
        const todayFile = existingToday instanceof import_obsidian.TFile ? existingToday : await this.plugin.app.vault.create("ops/today.md", "# Today\n\nDaily task log.\n\n## Tasks\n");
        const content = await this.plugin.app.vault.read(todayFile);
        const updated = insertUnderSection(content, "## Tasks", [routeLine], true);
        if (updated === content) {
          new import_obsidian.Notice("That task is already in Today's Tasks");
        } else {
          await this.plugin.app.vault.modify(todayFile, updated);
        }
      } catch (e) {
        console.error("[Command Center] Failed to save task:", e);
        new import_obsidian.Notice("Failed to save task \u2014 check console");
      }
      this.close();
      void ((_a = this.onSave) == null ? void 0 : _a.call(this));
    });
    input.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ScheduleTaskModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onSave) {
    super(app);
    this.detectedDomain = null;
    this.plugin = plugin;
    this.onSave = onSave;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cc-modal");
    contentEl.createEl("h2", { text: "Schedule Task", cls: "cc-modal-title" });
    const dateRow = contentEl.createDiv({ cls: "cc-schedule-date-row" });
    dateRow.createEl("label", { text: "DATE", cls: "cc-schedule-date-label" });
    const today = /* @__PURE__ */ new Date();
    const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
    const dateInput = dateRow.createEl("input", {
      type: "date",
      cls: "cc-schedule-date-input",
      attr: { value: dateStr }
    });
    const inputWrapper = contentEl.createDiv({ cls: "cc-modal-input-wrapper" });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "cc-modal-input",
      attr: { placeholder: "What needs to happen?" }
    });
    const routePreview = contentEl.createDiv({ cls: "cc-modal-route-preview" });
    routePreview.createSpan({ cls: "cc-modal-route-label", text: "Routes to: " });
    const routeTarget = routePreview.createSpan({ cls: "cc-modal-route-target", text: "none detected" });
    input.addEventListener("input", () => {
      const val = input.value.toLowerCase();
      this.detectedDomain = null;
      for (const [key, keywords] of Object.entries(DOMAIN_KEYWORDS)) {
        for (const kw of keywords) {
          if (val.includes(kw)) {
            this.detectedDomain = key;
            const domain = DOMAINS.find((d) => d.key === key);
            routeTarget.setText(domain ? domain.name : key);
            routeTarget.addClass("cc-modal-route-detected");
            return;
          }
        }
      }
      routeTarget.setText("none detected");
      routeTarget.removeClass("cc-modal-route-detected");
    });
    const btnRow = contentEl.createDiv({ cls: "cc-modal-btn-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel", cls: "cc-modal-btn cc-modal-btn-cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const addBtn = btnRow.createEl("button", { text: "Schedule", cls: "cc-modal-btn cc-modal-btn-add" });
    let submitting = false;
    addBtn.addEventListener("click", async () => {
      var _a;
      if (submitting)
        return;
      const text = input.value.trim();
      const date = dateInput.value;
      if (!text || !date)
        return;
      submitting = true;
      addBtn.disabled = true;
      const slug = this.detectedDomain || "";
      const routeLine = slug ? `- [ ] ${date} \u2192 ${text} \u2192 ${slug}` : `- [ ] ${date} \u2192 ${text}`;
      try {
        const scheduleFile = this.plugin.app.vault.getAbstractFileByPath("ops/schedule.md");
        if (scheduleFile && scheduleFile instanceof import_obsidian.TFile) {
          const content = await this.plugin.app.vault.read(scheduleFile);
          if (content.includes("## Upcoming")) {
            const lines = content.split("\n");
            let insertIdx = -1;
            let inUpcoming = false;
            for (let i = 0; i < lines.length; i++) {
              if (lines[i].trim() === "## Upcoming") {
                inUpcoming = true;
                continue;
              }
              if (inUpcoming) {
                if (lines[i].startsWith("## ")) {
                  insertIdx = i;
                  break;
                }
                if (lines[i].trim().startsWith("- [")) {
                  insertIdx = i + 1;
                }
              }
            }
            if (insertIdx === -1)
              insertIdx = lines.length;
            lines.splice(insertIdx, 0, routeLine);
            await this.plugin.app.vault.modify(scheduleFile, lines.join("\n"));
          } else {
            const updated = content + `

## Upcoming
${routeLine}`;
            await this.plugin.app.vault.modify(scheduleFile, updated);
          }
        }
      } catch (e) {
        console.error("[Command Center] Failed to schedule task:", e);
      }
      this.close();
      void ((_a = this.onSave) == null ? void 0 : _a.call(this));
    });
    input.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
function fmtDate(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function truncateText(text, maxLen) {
  if (text.length <= maxLen)
    return text;
  return text.substring(0, maxLen).trim() + "...";
}
var StatusSyncModal = class extends import_obsidian.Modal {
  constructor(app, plugin, handoffs, vaultStatuses, todo, onLogged) {
    super(app);
    this.plugin = plugin;
    this.handoffs = handoffs;
    this.vaultStatuses = vaultStatuses;
    this.todo = todo;
    this.onLogged = onLogged;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cc-modal");
    contentEl.addClass("cc-sync-modal");
    contentEl.createEl("h2", { text: "Status Sync", cls: "cc-modal-title" });
    contentEl.createDiv({ cls: "cc-sync-scanned", text: `Scanned ${HANDOFF_REPOS.length} session handoffs \xB7 ${fmtDate(/* @__PURE__ */ new Date())}` });
    const total = this.todo.open + this.todo.done;
    const pct = total > 0 ? Math.round(this.todo.done / total * 100) : 0;
    const filled = Math.round(pct / 5);
    const bar = "\u2588".repeat(filled) + "\u2591".repeat(20 - filled);
    const overdueNote = this.todo.overdue > 0 ? ` \xB7 ${this.todo.overdue} overdue` : "";
    const progressSection = contentEl.createDiv({ cls: "cc-sync-progress" });
    progressSection.createDiv({ cls: "cc-sync-progress-label", text: "TODAY'S TASKS" });
    progressSection.createDiv({
      cls: "cc-sync-progress-bar",
      text: `${bar} ${pct}% \u2014 ${this.todo.done}/${total} done${overdueNote}`
    });
    const list = contentEl.createDiv({ cls: "cc-sync-list" });
    for (const h of this.handoffs) {
      const row = list.createDiv({ cls: `cc-sync-row ${h.found ? "" : "cc-sync-row-missing"}` });
      const head = row.createDiv({ cls: "cc-sync-row-head" });
      head.createDiv({ cls: "cc-sync-row-name", text: h.name });
      if (h.found && h.lastUpdated) {
        head.createDiv({ cls: "cc-sync-row-date", text: h.lastUpdated });
      }
      if (!h.found) {
        row.createDiv({ cls: "cc-sync-row-snippet", text: "No SESSION_HANDOFF.md found" });
      } else if (h.snippet) {
        row.createDiv({ cls: "cc-sync-row-snippet", text: this.truncate(h.snippet, 180) });
      }
      if (h.found) {
        const meta = row.createDiv({ cls: "cc-sync-row-meta" });
        meta.createSpan({ text: `${h.openItems} open item${h.openItems !== 1 ? "s" : ""} in handoff` });
      }
    }
    const statusTitle = contentEl.createDiv({ cls: "cc-sync-progress-label", text: "PROJECT STATUS BLOCKS (STATUS.MD)" });
    statusTitle.addClass("cc-sync-status-heading");
    const statusList = contentEl.createDiv({ cls: "cc-sync-list" });
    for (const s of this.vaultStatuses) {
      const row = statusList.createDiv({ cls: `cc-sync-row ${s.found ? "" : "cc-sync-row-missing"}` });
      const head = row.createDiv({ cls: "cc-sync-row-head" });
      head.createDiv({ cls: "cc-sync-row-name", text: s.name });
      if (s.found && s.lastUpdated) {
        head.createDiv({ cls: "cc-sync-row-date", text: s.lastUpdated });
      }
      if (!s.found) {
        row.createDiv({ cls: "cc-sync-row-snippet", text: "No STATUS.md found" });
      } else if (s.phase) {
        row.createDiv({ cls: "cc-sync-row-snippet", text: this.truncate(s.phase, 180) });
      }
      if (s.found) {
        const meta = row.createDiv({ cls: "cc-sync-row-meta" });
        const bits = [];
        if (s.progressPct !== null)
          bits.push(`${s.progressPct}%`);
        bits.push(`${s.blockersOpen} blocker${s.blockersOpen !== 1 ? "s" : ""}`);
        meta.createSpan({ text: bits.join(" \xB7 ") });
      }
    }
    const btnRow = contentEl.createDiv({ cls: "cc-modal-btn-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Close", cls: "cc-modal-btn cc-modal-btn-cancel" });
    cancelBtn.addEventListener("click", () => this.close());
    const logBtn = btnRow.createEl("button", { text: "Log to Headlines", cls: "cc-modal-btn cc-modal-btn-add" });
    logBtn.addEventListener("click", async () => {
      var _a;
      logBtn.disabled = true;
      await this.logToHeadlines();
      new import_obsidian.Notice("Status sync logged to headlines.md");
      this.close();
      void ((_a = this.onLogged) == null ? void 0 : _a.call(this));
    });
    const writeBtn = btnRow.createEl("button", { text: "Update Project Status", cls: "cc-modal-btn cc-modal-btn-add" });
    writeBtn.addEventListener("click", async () => {
      var _a;
      writeBtn.disabled = true;
      const result = await this.writeStatusBlocks();
      if (result.updated.length > 0) {
        new import_obsidian.Notice(`Updated STATUS.md blocks for ${result.updated.join(", ")}`);
      } else {
        new import_obsidian.Notice("No project STATUS.md blocks updated \u2014 no matching handoffs found");
      }
      this.close();
      void ((_a = this.onLogged) == null ? void 0 : _a.call(this));
    });
    const dispatchBtn = btnRow.createEl("button", { text: `Dispatch Agent (${this.plugin.settings.syncCli})`, cls: "cc-modal-btn cc-modal-btn-add" });
    dispatchBtn.addEventListener("click", () => {
      this.dispatchAgent();
    });
    contentEl.focus();
  }
  truncate(text, maxLen) {
    return truncateText(text, maxLen);
  }
  async logToHeadlines() {
    const file = this.plugin.app.vault.getAbstractFileByPath("ops/headlines.md");
    if (!file || !(file instanceof import_obsidian.TFile))
      return;
    const content = await this.plugin.app.vault.read(file);
    const dateStr = fmtDate(/* @__PURE__ */ new Date());
    const total = this.todo.open + this.todo.done;
    const pct = total > 0 ? Math.round(this.todo.done / total * 100) : 0;
    const entryLines = [];
    entryLines.push(`### ${dateStr} \u2014 Status Sync Scan`);
    entryLines.push(
      `Scanned ${this.handoffs.filter((h) => h.found).length}/${this.handoffs.length} session handoffs + todo progress. Tasks: ${this.todo.done}/${total} done (${pct}%)` + (this.todo.overdue > 0 ? `, ${this.todo.overdue} scheduled overdue.` : ".")
    );
    for (const h of this.handoffs) {
      if (!h.found) {
        entryLines.push(`- **${h.name}** \u2014 no handoff found`);
        continue;
      }
      const datePart = h.lastUpdated ? `updated ${h.lastUpdated}` : "no date";
      entryLines.push(`- **${h.name}** \u2014 handoff ${datePart}, ~${h.openItems} open item(s): ${this.truncate(h.snippet || "no summary", 140)}`);
    }
    const lines = content.split("\n");
    let insertIdx = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trim() === "## Recent") {
        insertIdx = i + 1;
        break;
      }
    }
    if (insertIdx === -1)
      insertIdx = lines.length;
    lines.splice(insertIdx, 0, "", ...entryLines);
    await this.plugin.app.vault.modify(file, lines.join("\n"));
  }
  // Writes per-project sync blocks into each mapped STATUS.md from its session handoff,
  // and bumps the Last Updated date when the handoff is newer.
  async writeStatusBlocks() {
    const updated = [];
    const skipped = [];
    const now = /* @__PURE__ */ new Date();
    const stamp = `${fmtDate(now)} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
    for (const h of this.handoffs) {
      if (!h.found) {
        skipped.push(h.name);
        continue;
      }
      const domain = DOMAINS.find((d) => d.key === h.domain);
      if (!domain) {
        skipped.push(h.name);
        continue;
      }
      const statusPath = `${domain.path}/STATUS.md`;
      const file = this.plugin.app.vault.getAbstractFileByPath(statusPath);
      if (!file || !(file instanceof import_obsidian.TFile)) {
        skipped.push(h.name);
        continue;
      }
      const content = await this.plugin.app.vault.read(file);
      let lines = content.split("\n");
      if (h.lastUpdated) {
        const luIdx = lines.findIndex((l) => l.trim() === "## Last Updated");
        if (luIdx !== -1) {
          for (let j = luIdx + 1; j < lines.length; j++) {
            const t = lines[j].trim();
            if (!t)
              continue;
            const m = t.match(/(\d{4}-\d{2}-\d{2})/);
            if (m && m[1] < h.lastUpdated)
              lines[j] = lines[j].replace(m[1], h.lastUpdated);
            break;
          }
        }
      }
      const summary = this.truncate(h.statusLine || h.snippet || "no summary in handoff", 200);
      const block = [
        "## Sync Status",
        `- **Source:** \`${h.path}\`${h.lastUpdated ? ` (handoff updated ${h.lastUpdated})` : ""}`,
        `- **Handoff status:** ${summary}`,
        `- **Open items in handoff:** ~${h.openItems}`,
        `- **Last synced:** ${stamp}`
      ];
      const startIdx = lines.findIndex((l) => l.trim() === "## Sync Status");
      if (startIdx !== -1) {
        let endIdx = lines.length;
        for (let i = startIdx + 1; i < lines.length; i++) {
          if (/^#{1,2}\s+/.test(lines[i].trim())) {
            endIdx = i;
            break;
          }
        }
        lines.splice(startIdx, endIdx - startIdx, ...block);
      } else {
        lines = [...lines.filter((l, i) => !(i === lines.length - 1 && l.trim() === "")), "", ...block];
      }
      await this.plugin.app.vault.modify(file, lines.join("\n"));
      updated.push(h.name);
    }
    return { updated, skipped };
  }
  dispatchAgent() {
    const cli = this.plugin.settings.syncCli === "claude" ? "claude" : "opencode";
    const flag = cli === "claude" ? "-p" : "run";
    const flat = STATUS_SYNC_PROMPT.replace(/\s*\n\s*/g, " ");
    const quoted = `"${flat.replace(/"/g, "")}"`;
    const command = `${cli} ${flag} ${quoted}`;
    if (this.dispatchViaTermy(command, cli)) {
      this.close();
      return;
    }
    this.dispatchHeadless(command, cli);
  }
  // Runs the sync command visibly in a Termy terminal pane, if the termy plugin
  // is installed/enabled and exposes the runPresetScript API this relies on.
  // Returns false (without side effects) if Termy isn't usable, so the caller
  // can fall back to the headless spawn path.
  dispatchViaTermy(command, cli) {
    var _a, _b;
    try {
      const pluginsApi = this.plugin.app.plugins;
      if (!((_a = pluginsApi == null ? void 0 : pluginsApi.enabledPlugins) == null ? void 0 : _a.has("termy")))
        return false;
      const termy = (_b = pluginsApi.plugins) == null ? void 0 : _b["termy"];
      if (!termy || typeof termy.runPresetScript !== "function")
        return false;
      void termy.runPresetScript({
        id: "cc-status-sync",
        name: "Status Sync",
        actions: [{ id: "cc-status-sync-cmd", type: "terminal-command", value: command, enabled: true }],
        terminalTitle: "Status Sync",
        autoOpenTerminal: true,
        runInNewTerminal: false,
        showInStatusBar: false
      });
      new import_obsidian.Notice(`Status sync running in terminal via ${cli}`);
      return true;
    } catch (e) {
      return false;
    }
  }
  dispatchHeadless(command, cli) {
    try {
      const cp = require("child_process");
      const child = cp.spawn(command, {
        cwd: "D:\\OBSIDIAN\\COMMAND SUITE",
        windowsHide: true,
        shell: true,
        stdio: "ignore"
      });
      let reported = false;
      child.on("error", () => {
        if (!reported) {
          reported = true;
          new import_obsidian.Notice(`Failed to launch ${cli} \u2014 check CLI install/auth`);
        }
      });
      child.on("exit", (code) => {
        if (!reported && code !== 0) {
          reported = true;
          new import_obsidian.Notice(`${cli} status sync exited (code ${code != null ? code : "?"}) \u2014 check CLI auth`);
        }
      });
      new import_obsidian.Notice(`Status sync dispatched via ${cli} \u2014 running headless in the background`);
      this.close();
    } catch (e) {
      new import_obsidian.Notice("Could not dispatch agent \u2014 child_process unavailable");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.selectedCalendarDate = null;
    this.liveRefreshTimer = null;
    this.refreshQueue = Promise.resolve();
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Command Center";
  }
  getIcon() {
    return "layout-dashboard";
  }
  getViewData() {
    return "";
  }
  setViewData() {
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("cc-dashboard");
    await this.renderDashboard(container);
    const OPS_PATHS = ["ops/today.md", "ops/schedule.md", "ops/metrics.md", "ops/headlines.md"];
    this.registerEvent(
      this.app.vault.on("modify", (file) => this.onOpsFileChanged(file.path, OPS_PATHS))
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => this.onOpsFileChanged(file.path, OPS_PATHS))
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (OPS_PATHS.includes(oldPath) || OPS_PATHS.includes(file.path))
          this.queueLiveRefresh();
      })
    );
  }
  onOpsFileChanged(path, watchList) {
    if (!watchList.includes(path) && !path.endsWith("/STATUS.md"))
      return;
    this.queueLiveRefresh();
  }
  queueLiveRefresh() {
    if (this.liveRefreshTimer !== null)
      window.clearTimeout(this.liveRefreshTimer);
    this.liveRefreshTimer = window.setTimeout(() => {
      this.liveRefreshTimer = null;
      void this.refreshDashboard();
    }, 400);
  }
  async onClose() {
    const container = this.containerEl.children[1];
    container.empty();
  }
  async renderDashboard(container) {
    const settings = this.plugin.settings;
    if (settings.showHeroTile) {
      const hero = container.createDiv({ cls: "cc-hero" });
      const statCard = hero.createDiv({ cls: "cc-stat-card" });
      statCard.createDiv({ cls: "cc-stat-label", text: "PORTFOLIO" });
      const buildingCount = DOMAINS.filter((d) => d.status === "In Progress").length;
      const shippedCount = DOMAINS.filter((d) => d.status === "Complete").length;
      statCard.createDiv({ cls: "cc-stat-value", text: `${buildingCount} building / ${shippedCount} shipped` });
      const tasksCard = hero.createDiv({ cls: "cc-stat-card" });
      tasksCard.createDiv({ cls: "cc-stat-label", text: "OPEN TASKS" });
      const metricsContent = await this.readFromOps("metrics.md");
      const openTasks = this.countCheckedLines(metricsContent, "Open Tasks");
      tasksCard.createDiv({ cls: "cc-stat-value", text: openTasks });
      tasksCard.createDiv({ cls: "cc-stat-caption", text: "backlog \xB7 metrics.md" });
      const pipelineCard = hero.createDiv({ cls: "cc-stat-card" });
      pipelineCard.createDiv({ cls: "cc-stat-label", text: "PIPELINE" });
      const pipelineItems = this.extractListItems(metricsContent, "Pipeline Value");
      let inMotion = 0;
      let proposals = 0;
      for (const item of pipelineItems) {
        if (/\[(won|lost)\]/i.test(item))
          continue;
        inMotion++;
        if (/\[proposal\]/i.test(item))
          proposals++;
      }
      pipelineCard.createDiv({
        cls: "cc-stat-value",
        text: pipelineItems.length === 0 ? "Empty" : `${inMotion} in motion \xB7 ${proposals} proposal${proposals !== 1 ? "s" : ""}`
      });
      pipelineCard.createDiv({
        cls: "cc-stat-caption",
        text: pipelineItems.length === 0 ? "tag leads in metrics.md \u2014 [lead] [contacted] [proposal]" : "from metrics.md"
      });
    }
    if (settings.showHeatmap) {
      await this.renderHeatmap(container);
    }
    if (settings.showSchedulePanel) {
      await this.renderCalendarSection(container);
    }
    if (settings.showTodaySection) {
      await this.renderTodaySection(container);
    }
    if (settings.showSkillButtons) {
      this.renderSkills(container);
    }
    await this.renderDomainGrid(container);
    if (settings.showSessionSummary) {
      await this.renderSessionSummary(container);
    }
    await this.renderPanels(container);
  }
  /* ── Heatmap ── */
  async renderHeatmap(container) {
    const heatmapSection = container.createDiv({ cls: "cc-heatmap-section" });
    const header = heatmapSection.createDiv({ cls: "cc-heatmap-header" });
    header.createDiv({ cls: "cc-section-title", text: "ACTIVITY" });
    const syncWrapper = header.createDiv({ cls: "cc-sync-wrapper" });
    const lastSync = this.plugin.settings.lastSync;
    const syncLabel = lastSync > 0 ? this.timeAgo(lastSync) : "";
    const syncBtn = syncWrapper.createDiv({ cls: "cc-sync-btn", text: lastSync > 0 ? `\u27F3 SYNCED ${syncLabel}` : "\u27F3 SYNC" });
    syncBtn.addEventListener("click", async () => {
      syncBtn.setText("\u27F3 Syncing...");
      syncBtn.addClass("cc-sync-loading");
      await this.performSync();
      syncBtn.removeClass("cc-sync-loading");
      syncBtn.setText("\u2713 SYNCED just now");
      setTimeout(() => {
        syncBtn.setText(`\u27F3 SYNCED ${this.timeAgo(this.plugin.settings.lastSync)}`);
      }, 2e3);
    });
    const data = new Map(this.plugin.activityData);
    const today = /* @__PURE__ */ new Date();
    const startDate = new Date(today);
    startDate.setDate(startDate.getDate() - 52 * 7 + 1);
    const dayOfWeek = startDate.getDay();
    startDate.setDate(startDate.getDate() - dayOfWeek);
    let maxCount = 0;
    for (const count of data.values()) {
      if (count > maxCount)
        maxCount = count;
    }
    const totalWeeks = 52;
    const totalDays = totalWeeks * 7;
    const grid = heatmapSection.createDiv({ cls: "cc-heatmap-grid" });
    const monthsRow = grid.createDiv({ cls: "cc-heatmap-months" });
    monthsRow.createDiv({ cls: "cc-heatmap-month-spacer" });
    const monthsContainer = monthsRow.createDiv({ cls: "cc-heatmap-months-row" });
    const monthLabels = [];
    const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    let currentMonth = -1;
    const tempDate = new Date(startDate);
    for (let w = 0; w < totalWeeks; w++) {
      const month = tempDate.getMonth();
      if (month !== currentMonth) {
        monthLabels.push({ label: monthNames[month], weekIndex: w });
        currentMonth = month;
      }
      tempDate.setDate(tempDate.getDate() + 7);
    }
    let monthLabelIdx = 0;
    for (let w = 0; w < totalWeeks; w++) {
      const slot = monthsContainer.createDiv({ cls: "cc-heatmap-month-slot" });
      if (monthLabelIdx < monthLabels.length && monthLabels[monthLabelIdx].weekIndex === w) {
        slot.setText(monthLabels[monthLabelIdx].label);
        monthLabelIdx++;
      }
    }
    const mainRow = grid.createDiv({ cls: "cc-heatmap-main" });
    const dayLabels = mainRow.createDiv({ cls: "cc-heatmap-day-labels" });
    const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    for (let d = 0; d < 7; d++) {
      const label = dayLabels.createDiv({ cls: "cc-heatmap-day-label" });
      if (d % 2 === 1) {
        label.setText(dayNames[d]);
      }
    }
    const weeksContainer = mainRow.createDiv({ cls: "cc-heatmap-weeks" });
    const currentDate = new Date(startDate);
    for (let w = 0; w < totalWeeks; w++) {
      const weekCol = weeksContainer.createDiv({ cls: "cc-heatmap-week" });
      for (let d = 0; d < 7; d++) {
        const dateStr = this.formatDate(currentDate);
        const count = data.get(dateStr) || 0;
        const isFuture = currentDate > today;
        const cell = weekCol.createDiv({
          cls: `cc-heatmap-cell ${this.getIntensityClass(count, maxCount, isFuture)}`
        });
        cell.setAttribute("data-date", dateStr);
        cell.setAttribute("data-count", String(count));
        const tooltipDate = currentDate.toLocaleDateString("en-US", {
          weekday: "short",
          month: "short",
          day: "numeric",
          year: "numeric"
        });
        cell.setAttribute("title", `${count} contribution${count !== 1 ? "s" : ""} on ${tooltipDate}`);
        currentDate.setDate(currentDate.getDate() + 1);
      }
    }
    const footer = heatmapSection.createDiv({ cls: "cc-heatmap-footer" });
    const legend = footer.createDiv({ cls: "cc-heatmap-legend" });
    legend.createDiv({ cls: "cc-heatmap-legend-label", text: "Less" });
    for (let i = 0; i <= 4; i++) {
      legend.createDiv({
        cls: `cc-heatmap-cell cc-heatmap-level-${i === 0 ? "zero" : i}`
      });
    }
    legend.createDiv({ cls: "cc-heatmap-legend-label", text: "More" });
    let totalContributions = 0;
    for (const count of this.plugin.activityData.values()) {
      totalContributions += count;
    }
    const totalLabel = footer.createDiv({ cls: "cc-heatmap-total" });
    totalLabel.setText(`${totalContributions} contributions in the last ${totalWeeks} weeks`);
  }
  getIntensityClass(count, maxCount, isFuture) {
    if (isFuture)
      return "cc-heatmap-future";
    if (count === 0)
      return "cc-heatmap-level-zero";
    if (maxCount <= 4)
      return `cc-heatmap-level-${Math.min(count, 4)}`;
    const ratio = count / maxCount;
    if (ratio <= 0.25)
      return "cc-heatmap-level-1";
    if (ratio <= 0.5)
      return "cc-heatmap-level-2";
    if (ratio <= 0.75)
      return "cc-heatmap-level-3";
    return "cc-heatmap-level-4";
  }
  formatDate(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
  /* ── Today's Tasks ── */
  async renderTodaySection(container) {
    const todaySection = container.createDiv({ cls: "cc-today-section" });
    const todayHeader = todaySection.createDiv({ cls: "cc-today-header" });
    const titleCol = todayHeader.createDiv();
    titleCol.createDiv({ cls: "cc-section-title", text: "TODAY'S TASKS" });
    const metricsContent = await this.readFromOps("metrics.md");
    const backlogItems = this.extractListItems(metricsContent, "Open Tasks");
    const backlogOpen = backlogItems.filter((l) => l.includes("- [ ]")).length;
    titleCol.createDiv({
      cls: "cc-today-caption",
      text: `shortlist \u2014 full backlog: ${backlogOpen} open in metrics.md`
    });
    const addBtn = todayHeader.createDiv({ cls: "cc-today-add-btn", text: "+" });
    addBtn.addEventListener("click", () => {
      new TaskInputModal(this.plugin.app, this.plugin).open();
    });
    const todayContent = await this.readFromOps("today.md");
    const taskList = todaySection.createDiv({ cls: "cc-today-list" });
    if (todayContent) {
      const allLines = todayContent.split("\n");
      const taskRows = allLines.map((line, idx) => ({ line, idx })).filter((t) => t.line.trim().startsWith("- ["));
      if (taskRows.length === 0) {
        taskList.createDiv({ cls: "cc-today-empty", text: "No tasks yet. Click + to add one." });
      } else {
        taskRows.forEach(({ line, idx }) => {
          const isDone = /^\s*-\s*\[x\]/.test(line);
          const taskItem = taskList.createDiv({ cls: `cc-today-item ${isDone ? "cc-today-done" : ""}` });
          const readFreshLines = async () => {
            const todayFile = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
            if (!todayFile || !(todayFile instanceof import_obsidian.TFile))
              return null;
            const fresh = await this.plugin.app.vault.read(todayFile);
            return fresh.split("\n");
          };
          const resolveTaskIdx = (ls) => {
            if (ls[idx] === line)
              return idx;
            let best = -1;
            let bestDist = Infinity;
            for (let j = 0; j < ls.length; j++) {
              if (ls[j] === line) {
                const dist = Math.abs(j - idx);
                if (dist < bestDist) {
                  best = j;
                  bestDist = dist;
                }
              }
            }
            return best;
          };
          const checkbox = taskItem.createDiv({ cls: "cc-today-checkbox", text: isDone ? "\u25A0" : "\u25A1" });
          checkbox.addEventListener("click", async () => {
            const todayFile = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
            if (!todayFile || !(todayFile instanceof import_obsidian.TFile))
              return;
            const ls = await readFreshLines();
            if (!ls) {
              await this.refreshDashboard();
              return;
            }
            const i = resolveTaskIdx(ls);
            if (i === -1 || !ls[i].trim().startsWith("- [")) {
              await this.refreshDashboard();
              return;
            }
            const wasChecked = ls[i].includes("- [x]");
            ls[i] = ls[i].replace(wasChecked ? "- [x]" : "- [ ]", wasChecked ? "- [ ]" : "- [x]");
            await this.plugin.app.vault.modify(todayFile, ls.join("\n"));
          });
          const taskText = line.replace(/^-\s*\[[ x]\]\s*/, "");
          const parts = taskText.split("\u2192");
          const textEl = taskItem.createDiv({ cls: "cc-today-text" });
          textEl.createSpan({ text: parts[0].trim() });
          if (parts[1]) {
            textEl.createSpan({ cls: "cc-today-route", text: ` \u2192 ${parts[1].trim()}` });
          }
          const actions = taskItem.createDiv({ cls: "cc-today-actions" });
          const tomorrowBtn = actions.createDiv({ cls: "cc-today-action-btn cc-today-action-tomorrow", text: "\u2192" });
          tomorrowBtn.setAttribute("title", "Move to tomorrow");
          tomorrowBtn.addEventListener("click", async () => {
            const todayFile = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
            const scheduleFile = this.plugin.app.vault.getAbstractFileByPath("ops/schedule.md");
            if (!todayFile || !(todayFile instanceof import_obsidian.TFile))
              return;
            const tomorrow = /* @__PURE__ */ new Date();
            tomorrow.setDate(tomorrow.getDate() + 1);
            const dateStr = this.formatDate(tomorrow);
            const ls = await readFreshLines();
            if (!ls) {
              await this.refreshDashboard();
              return;
            }
            const i = resolveTaskIdx(ls);
            if (i === -1 || !ls[i].trim().startsWith("- [")) {
              await this.refreshDashboard();
              return;
            }
            const curTaskText = ls[i].replace(/^-\s*\[[ x]\]\s*/, "");
            const curParts = curTaskText.split("\u2192");
            const taskDesc = curParts[0].trim();
            const taskSlug = curParts[1] ? curParts[1].trim() : "";
            if (scheduleFile && scheduleFile instanceof import_obsidian.TFile) {
              const schedContent = await this.plugin.app.vault.read(scheduleFile);
              const routeLine = taskSlug ? `- [ ] ${dateStr} \u2192 ${taskDesc} \u2192 ${taskSlug}` : `- [ ] ${dateStr} \u2192 ${taskDesc}`;
              if (schedContent.includes("## Upcoming")) {
                const slines = schedContent.split("\n");
                let insertIdx = -1;
                for (let i2 = 0; i2 < slines.length; i2++) {
                  if (slines[i2].trim() === "## Upcoming")
                    continue;
                  if (slines[i2].trim().startsWith("- ["))
                    insertIdx = i2 + 1;
                }
                if (insertIdx === -1) {
                  insertIdx = slines.findIndex((l) => l.trim() === "## Upcoming") + 1;
                  if (insertIdx === 0)
                    insertIdx = slines.length;
                }
                slines.splice(insertIdx, 0, routeLine);
                await this.plugin.app.vault.modify(scheduleFile, slines.join("\n"));
              } else {
                const updated = schedContent + `

## Upcoming
${routeLine}`;
                await this.plugin.app.vault.modify(scheduleFile, updated);
              }
            }
            ls.splice(i, 1);
            await this.plugin.app.vault.modify(todayFile, ls.join("\n"));
          });
          const deleteBtn = actions.createDiv({ cls: "cc-today-action-btn cc-today-action-delete", text: "\xD7" });
          deleteBtn.setAttribute("title", "Delete task");
          deleteBtn.addEventListener("click", async () => {
            const ls = await readFreshLines();
            const todayFile = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
            if (!ls || !todayFile || !(todayFile instanceof import_obsidian.TFile)) {
              await this.refreshDashboard();
              return;
            }
            const i = resolveTaskIdx(ls);
            if (i === -1 || !ls[i].trim().startsWith("- [")) {
              await this.refreshDashboard();
              return;
            }
            ls.splice(i, 1);
            await this.plugin.app.vault.modify(todayFile, ls.join("\n"));
          });
        });
      }
    } else {
      taskList.createDiv({ cls: "cc-today-empty", text: "No tasks yet. Click + to add one." });
    }
  }
  /* ── Calendar / Schedule ── */
  async migrateScheduleToToday() {
    const scheduleFile = this.plugin.app.vault.getAbstractFileByPath("ops/schedule.md");
    const todayFile = this.plugin.app.vault.getAbstractFileByPath("ops/today.md");
    if (!scheduleFile || !(scheduleFile instanceof import_obsidian.TFile))
      return;
    if (!todayFile || !(todayFile instanceof import_obsidian.TFile))
      return;
    const scheduleContent = await this.plugin.app.vault.read(scheduleFile);
    const todayContent = await this.plugin.app.vault.read(todayFile);
    const todayStr = this.formatDate(/* @__PURE__ */ new Date());
    const scheduleLines = scheduleContent.split("\n");
    const migrated = [];
    const remaining = [];
    const existingTodayTasks = new Set(
      todayContent.split("\n").filter((l) => l.trim().startsWith("- [")).map((l) => l.replace(/^-\s*\[[ x]\]\s*/, "").trim())
    );
    for (const line of scheduleLines) {
      const match = line.match(/^-\s*\[[ x]\]\s*(\d{4}-\d{2}-\d{2})\s*→\s*(.+)/);
      if (match) {
        const taskDate = match[1];
        const taskBody = match[2].trim();
        if (line.includes("- [x]")) {
          remaining.push(line);
          continue;
        }
        const taskDateObj = /* @__PURE__ */ new Date(taskDate + "T00:00:00");
        const todayDateObj = /* @__PURE__ */ new Date(todayStr + "T00:00:00");
        if (taskDateObj <= todayDateObj) {
          if (!existingTodayTasks.has(taskBody)) {
            migrated.push(`- [ ] ${taskBody}`);
            existingTodayTasks.add(taskBody);
          }
          continue;
        }
      }
      remaining.push(line);
    }
    if (migrated.length > 0) {
      const updated = insertUnderSection(todayContent, "## Tasks", migrated, false);
      await this.plugin.app.vault.modify(todayFile, updated);
      await this.plugin.app.vault.modify(scheduleFile, remaining.join("\n"));
    }
  }
  async renderCalendarSection(container) {
    const section = container.createDiv({ cls: "cc-calendar-section" });
    const header = section.createDiv({ cls: "cc-calendar-header" });
    header.createDiv({ cls: "cc-section-title", text: "SCHEDULE" });
    const addBtn = header.createDiv({ cls: "cc-calendar-add-btn", text: "+ SCHEDULE" });
    addBtn.addEventListener("click", () => {
      new ScheduleTaskModal(this.plugin.app, this.plugin).open();
    });
    const body = section.createDiv({ cls: "cc-calendar-body" });
    const scheduleContent = await this.readFromOps("schedule.md");
    const today = /* @__PURE__ */ new Date();
    const todayStr = this.formatDate(today);
    const currentMonth = today.getMonth();
    const currentYear = today.getFullYear();
    const tasks = [];
    if (scheduleContent) {
      const lines = scheduleContent.split("\n");
      for (const line of lines) {
        const match = line.match(/^-\s*\[([ x])\]\s*(\d{4}-\d{2}-\d{2})\s*→\s*(.+)/);
        if (match) {
          const parts = match[3].split("\u2192");
          tasks.push({
            date: match[2],
            text: parts[0].trim(),
            slug: parts[1] ? parts[1].trim() : "",
            done: match[1] === "x"
          });
        }
      }
    }
    const taskDates = new Set(tasks.map((t) => t.date));
    const calLeft = body.createDiv({ cls: "cc-calendar-left" });
    let viewMonth = currentMonth;
    let viewYear = currentYear;
    if (this.selectedCalendarDate) {
      const sel = /* @__PURE__ */ new Date(this.selectedCalendarDate + "T12:00:00");
      viewMonth = sel.getMonth();
      viewYear = sel.getFullYear();
    }
    const renderMonth = () => {
      calLeft.empty();
      const nav = calLeft.createDiv({ cls: "cc-calendar-nav" });
      const prevBtn = nav.createDiv({ cls: "cc-calendar-nav-btn", text: "\u2039" });
      const monthLabel = nav.createDiv({ cls: "cc-calendar-month-label" });
      const monthNames = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
      monthLabel.setText(`${monthNames[viewMonth]} ${viewYear}`);
      const nextBtn = nav.createDiv({ cls: "cc-calendar-nav-btn", text: "\u203A" });
      prevBtn.addEventListener("click", () => {
        viewMonth--;
        if (viewMonth < 0) {
          viewMonth = 11;
          viewYear--;
        }
        renderMonth();
      });
      nextBtn.addEventListener("click", () => {
        viewMonth++;
        if (viewMonth > 11) {
          viewMonth = 0;
          viewYear++;
        }
        renderMonth();
      });
      const grid = calLeft.createDiv({ cls: "cc-calendar-grid" });
      for (const d of ["S", "M", "T", "W", "T", "F", "S"]) {
        grid.createDiv({ cls: "cc-calendar-day-header", text: d });
      }
      const firstDay = new Date(viewYear, viewMonth, 1).getDay();
      const daysInMonth = new Date(viewYear, viewMonth + 1, 0).getDate();
      for (let i = 0; i < firstDay; i++) {
        grid.createDiv({ cls: "cc-calendar-day cc-calendar-day-empty" });
      }
      for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${viewYear}-${String(viewMonth + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
        const isToday = dateStr === this.formatDate(today);
        const hasTask = taskDates.has(dateStr);
        const isPast = /* @__PURE__ */ new Date(dateStr + "T00:00:00") < /* @__PURE__ */ new Date(todayStr + "T00:00:00");
        const dayEl = grid.createDiv({
          cls: `cc-calendar-day ${isToday ? "cc-calendar-today" : ""} ${hasTask ? "cc-calendar-has-task" : ""} ${isPast && hasTask ? "cc-calendar-overdue" : ""}`,
          text: String(day)
        });
        if (hasTask) {
          dayEl.createDiv({ cls: "cc-calendar-dot" });
        }
        dayEl.addEventListener("click", () => {
          const wasAlreadySelected = dayEl.hasClass("cc-calendar-selected");
          grid.querySelectorAll(".cc-calendar-selected").forEach((el) => el.removeClass("cc-calendar-selected"));
          if (wasAlreadySelected) {
            this.selectedCalendarDate = null;
            renderUpcoming();
          } else {
            dayEl.addClass("cc-calendar-selected");
            this.selectedCalendarDate = dateStr;
            renderUpcoming(dateStr);
          }
        });
        if (this.selectedCalendarDate === dateStr) {
          dayEl.addClass("cc-calendar-selected");
        }
      }
    };
    renderMonth();
    const calRight = body.createDiv({ cls: "cc-calendar-right" });
    const renderUpcoming = (highlightDate) => {
      calRight.empty();
      if (highlightDate) {
        const dayTasks = tasks.filter((t) => t.date === highlightDate);
        const dateObj = /* @__PURE__ */ new Date(highlightDate + "T12:00:00");
        const label = calRight.createDiv({ cls: "cc-calendar-upcoming-label" });
        label.setText(this.formatDateShort(dateObj));
        if (dayTasks.length === 0) {
          calRight.createDiv({ cls: "cc-calendar-empty", text: "No tasks scheduled" });
        } else {
          const list = calRight.createDiv({ cls: "cc-calendar-upcoming-list" });
          for (const task of dayTasks) {
            const item = list.createDiv({ cls: "cc-calendar-upcoming-item" });
            const checkbox = item.createDiv({ cls: "cc-today-checkbox", text: task.done ? "\u25A0" : "\u25A1" });
            checkbox.addEventListener("click", async () => {
              await this.toggleScheduleTask(task, !task.done);
              await this.refreshDashboard();
            });
            const textEl = item.createDiv({ cls: "cc-today-text" });
            textEl.createSpan({ text: task.text });
            if (task.slug) {
              textEl.createSpan({ cls: "cc-today-route", text: ` \u2192 ${task.slug}` });
            }
          }
        }
      } else {
        const label = calRight.createDiv({ cls: "cc-calendar-upcoming-label" });
        label.setText("NEXT 14 DAYS");
        const todayStr2 = this.formatDate(today);
        const futureTasks = tasks.filter((t) => !t.done && t.date >= todayStr2).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 14);
        if (futureTasks.length === 0) {
          calRight.createDiv({ cls: "cc-calendar-empty", text: "No upcoming tasks" });
        } else {
          const list = calRight.createDiv({ cls: "cc-calendar-upcoming-list" });
          for (const task of futureTasks) {
            const item = list.createDiv({ cls: "cc-calendar-upcoming-item" });
            const dateObj = /* @__PURE__ */ new Date(task.date + "T12:00:00");
            const isOverdue = task.date < todayStr2;
            const dateBadge = item.createDiv({ cls: `cc-calendar-date-badge ${isOverdue ? "cc-calendar-overdue-badge" : ""}` });
            dateBadge.setText(this.formatDateShort(dateObj));
            const textEl = item.createDiv({ cls: "cc-today-text" });
            textEl.createSpan({ text: task.text });
            if (task.slug) {
              textEl.createSpan({ cls: "cc-today-route", text: ` \u2192 ${task.slug}` });
            }
          }
        }
      }
    };
    renderUpcoming(this.selectedCalendarDate || void 0);
  }
  async toggleScheduleTask(task, done) {
    const scheduleFile = this.plugin.app.vault.getAbstractFileByPath("ops/schedule.md");
    if (!scheduleFile || !(scheduleFile instanceof import_obsidian.TFile))
      return;
    const content = await this.plugin.app.vault.read(scheduleFile);
    const lines = content.split("\n");
    let matched = false;
    const updated = lines.map((line) => {
      const m = line.match(/^-\s*\[([ x])\]\s*(\d{4}-\d{2}-\d{2})\s*→\s*(.+)$/);
      if (!m)
        return line;
      const parts = m[3].split("\u2192");
      const text = parts[0].trim();
      const slug = parts[1] ? parts[1].trim() : "";
      if (m[2] !== task.date || text !== task.text || slug !== task.slug)
        return line;
      matched = true;
      return `- [${done ? "x" : " "}] ${task.date} \u2192 ${task.text}${task.slug ? ` \u2192 ${task.slug}` : ""}`;
    });
    if (matched) {
      await this.plugin.app.vault.modify(scheduleFile, updated.join("\n"));
    }
  }
  formatDateShort(date) {
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    return `${months[date.getMonth()]} ${date.getDate()}`;
  }
  /* ── Skills ── */
  renderSkills(container) {
    const skillsRow = container.createDiv({ cls: "cc-skills-row" });
    skillsRow.createDiv({ cls: "cc-section-title", text: "SKILLS" });
    const buttonsDiv = skillsRow.createDiv({ cls: "cc-skill-buttons" });
    const skills = [
      { id: "status-sync", name: "Status Sync", desc: "Daily project sync", cadence: "Daily" },
      { id: "handoff-writer", name: "Handoff Writer", desc: "Session handoff", cadence: "On-demand" },
      { id: "client-update", name: "Client Update", desc: "Oishii Nori", cadence: "On-demand" }
    ];
    skills.forEach((skill) => {
      const btn = buttonsDiv.createDiv({ cls: "cc-skill-btn" });
      btn.createDiv({ cls: "cc-skill-name", text: skill.name });
      btn.createDiv({ cls: "cc-skill-desc", text: `${skill.desc} \xB7 ${skill.cadence}` });
      btn.addEventListener("click", async () => {
        void this.logSkill(skill.id);
        void this.plugin.recordVaultActivity();
        if (skill.id === "status-sync") {
          const handoffs = scanHandoffs();
          const vaultStatuses = this.scanVaultStatusesSafe();
          const todo = await this.scanTodoProgress();
          new StatusSyncModal(this.plugin.app, this.plugin, handoffs, vaultStatuses, todo, () => this.refreshDashboard()).open();
        } else if (skill.id === "handoff-writer") {
          await this.runHandoffWriter();
        } else if (skill.id === "client-update") {
          await this.runClientUpdate();
        }
      });
    });
  }
  scanVaultStatusesSafe() {
    try {
      const adapter = this.plugin.app.vault.adapter;
      const vaultRoot = typeof adapter.getBasePath === "function" ? adapter.getBasePath() : "";
      if (!vaultRoot)
        return [];
      return scanVaultStatuses(vaultRoot);
    } catch (e) {
      console.error("[Command Center] STATUS.md scan failed:", e);
      return [];
    }
  }
  async scanTodoProgress() {
    const progress = { open: 0, done: 0, overdue: 0 };
    const todayStr = this.formatDate(/* @__PURE__ */ new Date());
    const todayContent = await this.readFromOps("today.md");
    if (todayContent) {
      for (const line of todayContent.split("\n")) {
        const t = line.trim();
        if (t.startsWith("- [ ]"))
          progress.open++;
        else if (t.startsWith("- [x]"))
          progress.done++;
      }
    }
    const schedContent = await this.readFromOps("schedule.md");
    if (schedContent) {
      for (const line of schedContent.split("\n")) {
        if (line.includes("- [x]"))
          continue;
        const m = line.match(/^-\s*\[[ x]\]\s*(\d{4}-\d{2}-\d{2})\s*→/);
        if (m && m[1] < todayStr)
          progress.overdue++;
      }
    }
    return progress;
  }
  async writeDraft(path, content) {
    try {
      const existing = this.plugin.app.vault.getAbstractFileByPath(path);
      if (existing instanceof import_obsidian.TFile) {
        await this.plugin.app.vault.modify(existing, content);
        return existing;
      }
      const folder = path.substring(0, path.lastIndexOf("/"));
      if (folder && !this.plugin.app.vault.getAbstractFileByPath(folder)) {
        await this.plugin.app.vault.createFolder(folder);
      }
      return await this.plugin.app.vault.create(path, content);
    } catch (e) {
      console.error("[Command Center] Failed to write draft:", e);
      new import_obsidian.Notice("Failed to write draft \u2014 check console");
      return null;
    }
  }
  async openFileInTab(file) {
    await this.plugin.app.workspace.getLeaf("tab").openFile(file);
  }
  /* ── Skill: Handoff Writer ── */
  async runHandoffWriter() {
    const dateStr = fmtDate(/* @__PURE__ */ new Date());
    const lines = [];
    lines.push(`# Session Handoff \u2014 ${dateStr}`);
    lines.push("");
    const todayContent = await this.readFromOps("today.md");
    const done = [];
    const open = [];
    if (todayContent) {
      for (const line of todayContent.split("\n")) {
        const t = line.trim();
        if (t.startsWith("- [x]"))
          done.push(t.replace(/^- \[x\]\s*/, ""));
        else if (t.startsWith("- [ ]"))
          open.push(t.replace(/^- \[ \]\s*/, ""));
      }
    }
    lines.push("## Completed Today");
    if (done.length > 0)
      for (const d of done)
        lines.push(`- ${d}`);
    else
      lines.push("- (nothing logged)");
    lines.push("");
    lines.push("## Still Open");
    if (open.length > 0)
      for (const o of open)
        lines.push(`- ${o}`);
    else
      lines.push("- (none)");
    lines.push("");
    lines.push("## Per-Domain Status");
    for (const domain of DOMAINS) {
      if (!this.plugin.settings.visibleDomains[domain.key])
        continue;
      const statusContent = await this.readFromFile(`${domain.path}/STATUS.md`);
      if (!statusContent)
        continue;
      const summary = this.extractSection(statusContent, "Last Session Summary");
      const updated = this.extractField(statusContent, "Last Updated");
      lines.push(`### ${domain.name}${updated ? ` (${updated})` : ""}`);
      lines.push(summary || "No summary yet.");
      lines.push("");
    }
    lines.push("## Recent Headlines");
    const headlinesContent = await this.readFromOps("headlines.md");
    if (headlinesContent) {
      const entries = headlinesContent.split("\n").filter((l) => l.trim().startsWith("### ")).slice(0, 3);
      for (const e of entries)
        lines.push(e.replace(/^###\s*/, "- "));
    }
    lines.push("");
    let changelogCount = 0;
    const bySlug = /* @__PURE__ */ new Map();
    for (const d of done) {
      const parts = d.split("\u2192");
      const slug = parts[1] ? parts[1].trim().toLowerCase() : "";
      if (slug && DOMAINS.some((x) => x.key === slug)) {
        if (!bySlug.has(slug))
          bySlug.set(slug, []);
        bySlug.get(slug).push(parts[0].trim());
      }
    }
    for (const [slug, entries] of bySlug) {
      const domain = DOMAINS.find((x) => x.key === slug);
      const f = this.plugin.app.vault.getAbstractFileByPath(`${domain.path}/STATUS.md`);
      if (!(f instanceof import_obsidian.TFile))
        continue;
      try {
        let c = await this.plugin.app.vault.read(f);
        const dayPrefix = `- ${dateStr} \u2014 `;
        const cl = c.split("\n");
        let merged = false;
        for (let k = 0; k < cl.length; k++) {
          if (cl[k].startsWith(dayPrefix)) {
            const prevEntries = cl[k].slice(dayPrefix.length).split(";").map((s) => s.trim()).filter(Boolean);
            cl[k] = dayPrefix + Array.from(/* @__PURE__ */ new Set([...prevEntries, ...entries])).join("; ");
            merged = true;
            break;
          }
        }
        if (merged) {
          c = cl.join("\n");
        } else {
          const stamp = (dayPrefix + entries.join("; ")).replace(/\$/g, "$$$$");
          if (/^## Changelog\s*$/im.test(c)) {
            c = c.replace(/^(## Changelog)\s*$/im, `$1
${stamp}`);
          } else {
            c = c.trimEnd() + `

## Changelog
${stamp}
`;
          }
        }
        await this.plugin.app.vault.modify(f, c);
        changelogCount++;
      } catch (e) {
        console.error(`[Command Center] changelog append failed for ${domain.name}:`, e);
      }
    }
    const file = await this.writeDraft(`inbox/SESSION_HANDOFF-draft-${dateStr}.md`, lines.join("\n"));
    if (file) {
      new import_obsidian.Notice(changelogCount > 0 ? `Handoff draft written \xB7 ${changelogCount} project changelog${changelogCount !== 1 ? "s" : ""} updated` : "Handoff draft written to inbox/");
      await this.openFileInTab(file);
    }
  }
  /* ── Skill: Client Update Composer ── */
  async runClientUpdate() {
    const dateStr = fmtDate(/* @__PURE__ */ new Date());
    const statusContent = await this.readFromFile("projects/varix/oishii-nori/STATUS.md");
    if (!statusContent) {
      new import_obsidian.Notice("No Oishii Nori STATUS.md found");
      return;
    }
    const summary = this.extractSection(statusContent, "Last Session Summary");
    const phase = this.extractSection(statusContent, "Current Phase");
    const blockers = this.extractListItems(statusContent, "Key Blockers");
    const lines = [];
    lines.push(`# Client Update \u2014 Oishii Nori \u2014 ${dateStr}`);
    lines.push("");
    lines.push("Hi! Here's a quick update on where things stand:");
    lines.push("");
    if (summary) {
      lines.push("**What we worked on recently**");
      lines.push(summary);
      lines.push("");
    }
    if (phase) {
      lines.push("**Current phase**");
      lines.push(phase);
      lines.push("");
    }
    if (blockers.length > 0) {
      lines.push("**What's next**");
      for (const b of blockers) {
        lines.push(b.replace(/^-\s*\[[ x]\]\s*/, "").replace(/^-\s*/, ""));
      }
      lines.push("");
    }
    lines.push("Let me know if you have any questions or want to reprioritize anything.");
    const file = await this.writeDraft(`inbox/client-update-oishii-nori-${dateStr}.md`, lines.join("\n"));
    if (file) {
      new import_obsidian.Notice("Client update draft written to inbox/");
      await this.openFileInTab(file);
    }
  }
  /* ── Domain Grid ── */
  async renderDomainGrid(container) {
    const settings = this.plugin.settings;
    const states = [];
    for (const domain of DOMAINS) {
      if (!settings.visibleDomains[domain.key])
        continue;
      const content = await this.readFromFile(`${domain.path}/STATUS.md`);
      const lastUpdated = content ? this.extractField(content, "Last Updated") : "";
      const { blocked, reason } = content ? this.parseBlocked(content) : { blocked: false, reason: "" };
      states.push({ domain, content, lastUpdated, blocked, reason });
    }
    const blockedStates = states.filter((s) => s.blocked);
    if (blockedStates.length > 0) {
      const lane = container.createDiv({ cls: "cc-blocked-lane" });
      lane.createDiv({ cls: "cc-section-title", text: `BLOCKED (${blockedStates.length})` });
      const laneBody = lane.createDiv({ cls: "cc-panel-body" });
      for (const b of blockedStates) {
        const row = laneBody.createDiv({ cls: "cc-blocked-row" });
        row.createDiv({ cls: "cc-blocked-name", text: b.domain.name });
        row.createDiv({ cls: "cc-blocked-reason", text: b.reason || "No reason logged" });
      }
    }
    const domainGrid = container.createDiv({ cls: "cc-domain-grid" });
    for (const state of states) {
      const domain = state.domain;
      const tile = domainGrid.createDiv({
        cls: `cc-domain-tile ${state.blocked ? "cc-domain-blocked" : ""}`
      });
      tile.addEventListener("click", async (e) => {
        if (e.target.closest(".cc-domain-live-btn"))
          return;
        const folder = this.plugin.app.vault.getAbstractFileByPath(domain.path);
        if (folder) {
          await this.plugin.app.workspace.getLeaf("tab").openFile(folder);
        }
      });
      const header = tile.createDiv({ cls: "cc-domain-header" });
      header.createDiv({ cls: "cc-domain-name", text: domain.name });
      const headerRight = header.createDiv({ cls: "cc-domain-header-right" });
      if (domain.liveUrl) {
        const liveBtn = headerRight.createDiv({ cls: "cc-domain-live-btn" });
        liveBtn.setText("\u2197 LIVE");
        liveBtn.setAttribute("title", domain.liveUrl);
        liveBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          window.open(domain.liveUrl, "_blank");
        });
      }
      const health = this.getHealth(state.lastUpdated);
      const healthLabel = health === "green" ? `synced ${state.lastUpdated}` : health === "yellow" ? `stale \u2014 last synced ${state.lastUpdated}` : state.lastUpdated ? `overdue \u2014 last synced ${state.lastUpdated}` : "never synced";
      const healthDot = headerRight.createDiv({ cls: `cc-health-dot cc-health-${health}` });
      healthDot.setAttribute("title", `Sync health: ${healthLabel}`);
      const statusClass = domain.status === "Complete" ? "cc-complete" : domain.status === "Planning" ? "cc-planning" : "cc-progress";
      const statusBadge = headerRight.createDiv({ cls: `cc-domain-status ${statusClass}` });
      statusBadge.setText(domain.status);
      if (state.blocked) {
        const blockedBadge = headerRight.createDiv({ cls: "cc-domain-status cc-blocked-badge" });
        blockedBadge.setText("BLOCKED");
      }
      const body = tile.createDiv({ cls: "cc-domain-body" });
      if (state.content) {
        const summary = this.extractSection(state.content, "Last Session Summary");
        if (summary) {
          body.createDiv({ cls: "cc-domain-summary", text: this.truncate(summary, 160) });
        } else {
          body.createDiv({ cls: "cc-domain-empty", text: "No summary yet" });
        }
        const blockers = this.extractListItems(state.content, "Key Blockers");
        if (blockers.length > 0) {
          const blockerEl = body.createDiv({ cls: "cc-domain-blockers" });
          blockerEl.createDiv({ cls: "cc-domain-blocker-label", text: `${blockers.length} blocker(s)` });
        }
      } else {
        body.createDiv({ cls: "cc-domain-empty", text: "No STATUS.md yet" });
      }
    }
  }
  /* ── Session Summary ── */
  async renderSessionSummary(container) {
    const settings = this.plugin.settings;
    const summaryPanel = container.createDiv({ cls: "cc-panel cc-session-summary" });
    summaryPanel.createDiv({ cls: "cc-section-title", text: "SESSION SUMMARIES" });
    const summaryBody = summaryPanel.createDiv({ cls: "cc-panel-body" });
    for (const domain of DOMAINS) {
      if (!settings.visibleDomains[domain.key])
        continue;
      const statusContent = await this.readFromFile(`${domain.path}/STATUS.md`);
      if (statusContent) {
        const summary = this.extractSection(statusContent, "Last Session Summary");
        const lastUpdated = this.extractField(statusContent, "Last Updated");
        const row = summaryBody.createDiv({ cls: "cc-summary-row" });
        const health = this.getHealth(lastUpdated);
        const dot = row.createDiv({ cls: `cc-health-dot cc-health-${health}` });
        dot.setAttribute("title", health === "green" ? `Synced ${lastUpdated}` : `Stale \u2014 last synced ${lastUpdated || "never"}`);
        row.createDiv({ cls: "cc-summary-label", text: domain.name });
        row.createDiv({ cls: "cc-summary-text", text: summary ? this.truncate(summary, 200) : "No data" });
        if (lastUpdated) {
          row.createDiv({ cls: "cc-summary-date", text: lastUpdated });
        }
      }
    }
  }
  /* ── Panels ── */
  async renderPanels(container) {
    const settings = this.plugin.settings;
    const panelsRow = container.createDiv({ cls: "cc-panels-row" });
    if (settings.showHeadlinesPanel) {
      const headlinesPanel = panelsRow.createDiv({ cls: "cc-panel" });
      headlinesPanel.createDiv({ cls: "cc-section-title", text: "HEADLINES" });
      const headlinesContent = await this.readFromOps("headlines.md");
      const body = headlinesPanel.createDiv({ cls: "cc-panel-body" });
      if (headlinesContent) {
        const lines = headlinesContent.split("\n").filter((l) => l.trim() && !l.startsWith("#")).slice(0, 10);
        lines.forEach((line) => body.createDiv({ cls: "cc-panel-line", text: line }));
      } else {
        body.createDiv({ cls: "cc-panel-empty", text: "No data yet" });
      }
    }
  }
  /* ── Utilities ── */
  async performSync() {
    this.plugin.refreshActivityData();
    this.plugin.settings.lastSync = Date.now();
    await this.plugin.saveSettings();
    await this.refreshDashboard();
  }
  timeAgo(timestamp) {
    const seconds = Math.floor((Date.now() - timestamp) / 1e3);
    if (seconds < 60)
      return "just now";
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60)
      return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24)
      return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
  }
  refreshDashboard() {
    this.refreshQueue = this.refreshQueue.then(() => this.doRefresh());
    return this.refreshQueue;
  }
  async doRefresh() {
    try {
      await this.migrateScheduleToToday();
      const container = this.containerEl.children[1];
      if (!container)
        return;
      container.empty();
      container.addClass("cc-dashboard");
      await this.renderDashboard(container);
    } catch (e) {
      console.error("[Command Center] Dashboard refresh failed:", e);
    }
  }
  async readFromOps(filename) {
    return this.readFromFile(`ops/${filename}`);
  }
  async readFromFile(path) {
    try {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file && file instanceof import_obsidian.TFile) {
        return await this.app.vault.read(file);
      }
    } catch (e) {
    }
    return "";
  }
  extractSection(content, sectionName) {
    if (!content)
      return "";
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes(sectionName)) {
        const collected = [];
        for (let j = i + 1; j < lines.length; j++) {
          const line = lines[j];
          if (line.startsWith("#") && !line.startsWith("##"))
            break;
          if (line.startsWith("## ") && !line.includes(sectionName))
            break;
          if (line.trim() && !line.startsWith("##"))
            collected.push(line.trim());
        }
        return collected.join(" ");
      }
    }
    return "";
  }
  extractListItems(content, sectionName) {
    if (!content)
      return [];
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes(sectionName)) {
        const items = [];
        for (let j = i + 1; j < lines.length; j++) {
          const line = lines[j].trim();
          if (line.startsWith("## ") || line.startsWith("#") && !line.startsWith("##"))
            break;
          if (line.startsWith("- ["))
            items.push(line);
        }
        return items;
      }
    }
    return [];
  }
  extractField(content, fieldName) {
    if (!content)
      return "";
    const lines = content.split("\n");
    const fieldPat = new RegExp(`^[\\s>#*-]*\\**${fieldName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\**\\s*(:|$)`, "i");
    for (let i = 0; i < lines.length; i++) {
      if (!fieldPat.test(lines[i]))
        continue;
      const parts = lines[i].split(":");
      const inlineVal = parts.length > 1 ? parts.slice(1).join(":").replace(/\*+/g, "").trim() : "";
      if (inlineVal)
        return inlineVal;
      for (let j = i + 1; j < lines.length; j++) {
        const t = lines[j].trim();
        if (!t)
          continue;
        if (t.startsWith("#"))
          return "";
        return t.replace(/^#+\s*/, "").replace(/\*+/g, "").trim().slice(0, 40);
      }
      return "";
    }
    return "";
  }
  countCheckedLines(content, sectionName) {
    const items = this.extractListItems(content, sectionName);
    const unchecked = items.filter((l) => l.includes("- [ ]")).length;
    const checked = items.filter((l) => l.includes("- [x]")).length;
    if (items.length === 0)
      return "No data yet";
    return `${unchecked} open / ${checked} done`;
  }
  truncate(text, maxLen) {
    return truncateText(text, maxLen);
  }
  /* ── Health & Blocked ── */
  getHealth(lastUpdated) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(lastUpdated))
      return "red";
    const days = Math.floor((Date.now() - (/* @__PURE__ */ new Date(lastUpdated + "T00:00:00")).getTime()) / 864e5);
    if (days <= this.plugin.settings.staleDays)
      return "green";
    if (days <= this.plugin.settings.criticalDays)
      return "yellow";
    return "red";
  }
  parseBlocked(content) {
    if (!content)
      return { blocked: false, reason: "" };
    const m = content.match(/^[\s>*~-]*\**status\**\s*::?\s*\**blocked\**\s*(?:[-—:.]\s*(.+))?$/im);
    if (!m)
      return { blocked: false, reason: "" };
    const reason = (m[1] || this.extractField(content, "Blocked Reason") || "").replace(/\*+/g, "").trim();
    return { blocked: true, reason };
  }
  /* ── Skill Trigger Log ── */
  async logSkill(skillId) {
    try {
      const path = "ops/skills-log.md";
      const now = /* @__PURE__ */ new Date();
      const line = `- ${fmtDate(now)} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")} \u2014 ${skillId} \xB7 dashboard click`;
      const existing = this.plugin.app.vault.getAbstractFileByPath(path);
      if (existing instanceof import_obsidian.TFile) {
        const c = await this.plugin.app.vault.read(existing);
        await this.plugin.app.vault.modify(existing, c.trimEnd() + "\n" + line + "\n");
      } else {
        await this.plugin.app.vault.create(path, "# Skill Trigger Log\n\n" + line + "\n");
      }
    } catch (e) {
      console.error("[Command Center] skill log failed:", e);
    }
  }
};
var CommandCenterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Command Center Settings" });
    containerEl.createEl("h3", { text: "Dashboard Sections" });
    const toggles = [
      ["Portfolio snapshot tile", "showHeroTile"],
      ["Activity heatmap", "showHeatmap"],
      ["Today's tasks section", "showTodaySection"],
      ["Skill buttons row", "showSkillButtons"],
      ["Session summaries", "showSessionSummary"],
      ["Schedule panel", "showSchedulePanel"],
      ["Headlines panel", "showHeadlinesPanel"]
    ];
    for (const [label, key] of toggles) {
      new import_obsidian.Setting(containerEl).setName(label).setToggleText("Show").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings[key]).onChange(async (value) => {
          this.plugin.settings[key] = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "Startup" });
    new import_obsidian.Setting(containerEl).setName("Open dashboard on startup").setDesc("Automatically open the Command Center when Obsidian launches").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openOnStartup).onChange(async (value) => {
        this.plugin.settings.openOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Status Sync" });
    new import_obsidian.Setting(containerEl).setName("Headless CLI").setDesc("Agent dispatched when running a full status sync from the skill button").addDropdown(
      (dropdown) => dropdown.addOption("opencode", "OpenCode").addOption("claude", "Claude Code").setValue(this.plugin.settings.syncCli).onChange(async (value) => {
        this.plugin.settings.syncCli = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Sync Health Flags" });
    new import_obsidian.Setting(containerEl).setName("Green threshold (days)").setDesc("Synced within this many days = green dot").addText(
      (text) => text.setValue(String(this.plugin.settings.staleDays)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n >= 0) {
          this.plugin.settings.staleDays = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Red threshold (days)").setDesc("Over this many days since last sync = red dot (between = yellow)").addText(
      (text) => text.setValue(String(this.plugin.settings.criticalDays)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n >= 0) {
          this.plugin.settings.criticalDays = n;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Domain Tiles" });
    for (const domain of DOMAINS) {
      new import_obsidian.Setting(containerEl).setName(domain.name).setDesc(domain.status).addToggle(
        (toggle) => {
          var _a;
          return toggle.setValue((_a = this.plugin.settings.visibleDomains[domain.key]) != null ? _a : true).onChange(async (value) => {
            this.plugin.settings.visibleDomains[domain.key] = value;
            await this.plugin.saveSettings();
          });
        }
      );
    }
  }
};
